Fix DeprecatedEdxPlatformImportWarning
mitodl/edx-sga pull request #286
Opened 2020-11-20 18:17 UTC by morenol

#### What are the relevant tickets?
(Required)

#### What's this PR do?
This PR would remove this warning that occurs in Studio every time that the service is run.
```python
2020-11-20 18:04:24,829 WARNING 78 [py.warnings] [user None] [ip None] warnings.py:109 - /edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/edx_sga/tasks.py:15: DeprecatedEdxPlatformImportWarning: Importing student.models instead of common.djangoapps.student.models is deprecated
  from student.models import user_by_anonymous_id
```

You can test this by running the devstack this:

make studio-shell
/edx/bin/edxapp-shell-cms

This should throw the DeprecatedEdxPlatformImportWarning warning. Then, install this version of edx-sga and the warning should dissapear.

Related PRs: https://github.com/edx/edx-platform/pull/25477

#### Any background context you want to provide?
https://discuss.openedx.org/t/squash-a-warning-earn-a-badge/3497/13

2020-11-26 09:22 UTC, HamzaIbnFarooq requested changes
@morenol Thanks for your contribution, we really appreciate your effort.
In the PR a few pylint issues have occurred with module not found error. Can you please add `no-name-in-module` under `disable` section in `pylintrc` and re-push?

2020-11-26 14:20 UTC, pdpinch commented
Thanks for the contribution @morenol! 

Can you please remove the version number change? Our release bot takes care of that and you will confuse it.

2020-11-26 14:21 UTC, morenol commented
@HamzaIbnFarooq done!, I added that to the pylintrc_tweaks file and generated a new pylint file with `edx_lint write pylintrc`

2020-11-26 14:22 UTC, morenol commented
> Thanks for the contribution @morenol!
> 
> Can you please remove the version number change? Our release bot takes care of that and you will confuse it.

sure, I will remove that now!

2020-11-27 08:24 UTC, HamzaIbnFarooq approved these changes
LGTM 👍 
Kindly squash commits and merge.

2020-11-30 05:06 UTC, merged