upgrading celery==5.0.5
mitodl/edx-sga pull request #293
Opened 2021-01-11 15:07 UTC by awais786

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2021-01-11 15:37 UTC, awais786 commented
@pdpinch Please review.

2021-01-11 15:38 UTC, awais786 commented on .github/workflows/ci.yml
> +on:
Now tests will run against all prs.

2021-01-12 08:56 UTC, umarmughal824 approved these changes
👍

2021-01-12 14:21 UTC, umarmughal824 commented
@awais786 I have noticed that you have forked that repo and opened the PR from there. Normally, that code works fine and runs tests on our local repo PR's.

By specifying the branches and pull requests that way, I have doubt it would run the tests only against the master branch PRs.

2021-01-19 16:07 UTC, umarmughal824 requested changes
Just a minor change.

2021-01-19 16:07 UTC, umarmughal824 commented on .github/workflows/ci.yml
> +on:
```suggestion
on: [push, pull_request]
```

2021-01-19 16:07 UTC, umarmughal824 commented on .github/workflows/ci.yml
> +  push:
```suggestion
```

2021-01-19 16:07 UTC, umarmughal824 commented on .github/workflows/ci.yml
> +    branches: [ master ]
```suggestion
```

2021-01-19 16:07 UTC, umarmughal824 commented on .github/workflows/ci.yml
> +  pull_request:
```suggestion
```

2021-01-19 16:07 UTC, umarmughal824 commented on .github/workflows/ci.yml
> +    branches: [ master ]
```suggestion
```

2021-01-19 16:13 UTC, umarmughal824 commented
@awais786 we only need to update update on feature like `on: [push, pull_request]` to run the tests for the forked repository PR.

Here is the test PR for the test that the tests are running. https://github.com/mitodl/edx-sga/pull/294/files

2021-01-20 06:48 UTC, umarmughal824 approved these changes

2021-01-20 06:56 UTC, merged